### ISSUE TITLE
microtime

### ISSUE THREAD

**Issue by tjvr** [robertklep/node-benchr#5]
What is microtime used for, and is it possible to make it an optional dependency? On some platforms it fails to install :-)

**Comment by robertklep** [comment]
It's listed as an optional install for `benchmark`, but by the looks of it, `benchmark` will just as easily use `process.hrtime()`, which would make `microtime` unnecessary.

I'll remove it as a dependency.

**Comment by robertklep** [comment]
Pushed v3.4.0

**Comment by tjvr** [comment]
Great, thanks :-)
