### ISSUE TITLE
HTML exports

### ISSUE THREAD

**Issue by danielo515** [robertklep/node-benchr#6]
Hello,

Thank you very much, your library has saved me a lot of time on building my own benchmark suite on top of Benchmark.js. People seems to be worried about browser performance, but what about node ? So thanks.

I want to use your tool as a base to teach my team good practices. In order to do so, I can just run the test in front of them, or I can accumulate the results and point them to them.
I think it would be ideal if I can just show the test running on-live but also have a repository of benchmark results that I can just serve from a basic static server as reference.

If you implement an html reporter ( ideally with graphs) that will be ideal. Something like jsperf does but for node.
If you don't have the time for such task, maybe you can just create a reporter API and allow us to build our own reporter.

Thanks !!

**Comment by robertklep** [comment]
Glad to hear you find my tool useful!

A reporter API is something that I've had on the TODO list for quite some time now, but never got around to implementing.

I'll see if I can find some time next week to implement an API.

**Comment by danielo515** [comment]
Let me know if you need any help.
Any particular place to look at?

**Comment by robertklep** [comment]
My initial thought is that in order to get this up and running quickly, I could add an option to output the benchmark data as JSON. Would that be sufficient for you as a (relatively) short-term solution?

**Comment by danielo515** [comment]
That will totally fix my problem of comparing and storing benchmarks. I think it is the best possible step towards a long term benchmarking system.
Having that I can try to store them on a database and/or try to use any graphing tool available. 

Regards

**Comment by robertklep** [comment]
Cool, thanks for the feedback! I'll see if I can work on it a bit tomorrow.

**Comment by robertklep** [comment]
By the way, I'm thinking about rewriting the runner so it's a proper class (`class Runner { ... }`). 

However, this means Node v4 as a minimal requirement. Is that an issue for you? If so, I won't do the rewrite.

**Comment by danielo515** [comment]
My target is node 8, and I'll always aim at the newer version.
In any case, you can go for it and if backwards compatibility is required I can make you a PR adding transpiling for older versions of node (in exchange for your support on this matter). The package.json has plenty of tricks for this kind of stuff

**Comment by danielo515** [comment]
Now that the JSON reporter is close to be a reality I can handle this myself.
