### ISSUE TITLE
Add a require option to benchmark ES next source code

### ISSUE THREAD

**Issue by frenzzy** [robertklep/node-benchr#8]
- `-r`, `--require` `<name>` require the given module
```js
benchr benchmark.js --require @babel/register
```

**Comment by robertklep** [comment]
Nice idea! I'll see if it's easy to implement.

**Comment by robertklep** [comment]
I just pushed v4.3.0 which supports this option.

**Comment by frenzzy** [comment]
Awesome! Thank you!
